TARJETAS =    [
    {"tema": "Uso de 'could'", "regla": "Habilidades pasadas. Ej: I could swim."},
    {"tema": "Regla de 'enjoy'", "regla": "Siempre usa -ing. Ej: I enjoy reading."},
    {"tema": "Voz Pasiva", "regla": "Objeto + is/are + participio. Ej: Cars are made."},
    {"tema": "Uso de 'could'", "detail": "Habilidades generales en el pasado.\nEj: When I was young, I could swim."},
    {"tema": "Diferencia 'can' vs 'could'", "detail": "Can = Presente (I can swim).\nCould = Pasado (I could swim)."},
    {"tema": "Presente Perfecto (Duración)", "detail": "Sujeto + have/has + participio + for/since.\nAcciones que siguen vigentes."},
    {"tema": "Uso de 'for' y 'since'", "detail": "For = Período de tiempo (for 3 years).\nSince = Punto de inicio (since 2023)."},
    {"tema": "Primer Condicional", "detail": "If + Presente Simple, will/won't + infinitivo.\nSituaciones futuras probables."},
    {"tema": "Significado: 'won't' vs 'wouldn't'", "detail": "Won't = Futuro probable (1st cond.).\nWouldn't = Hipotético/Imaginario (2nd cond.)."},
    {"tema": "Pronombre relativo: Objeto/Animal", "detail": "Se usa 'which' o 'that'.\nEj: The book which I bought yesterday."},
    {"tema": "Pronombre relativo: 'whose'", "detail": "Significa 'cuyo/a'. Denota posesión.\nEj: The girl whose dog is barking."},
    {"tema": "Pronombre relativo: 'who'", "detail": "Se usa exclusivamente para personas.\nEj: The teacher who lives next door."},
    {"tema": "Pasado Continuo + Pasado Simple", "detail": "Pasado continuo (acción larga) interrumpida por Pasado simple (corta)."},
    {"tema": "Comparativos cortos en 'y'", "detail": "Cambia 'y' por 'i' y añade '-er'.\nEj: easy -> easier / happy -> happier."},
    {"tema": "Error común: 'more easier'", "detail": "¡Incocto! Con adjetivos cortos no se usa 'more'. Se dice solo 'easier'."},
    {"tema": "Uso de 'should'", "detail": "Para dar consejos o sugerencias.\nEj: You should see a doctor if you feel sick."},
    {"tema": "Diferencia 'should' vs 'might'", "detail": "Should = Consejo (Deberías).\nMight = Probabilidad remota (Podría ser)."},
    {"tema": "Incontables en negativo", "detail": "Se usa 'much' para cosas que no se cuentan.\nEj: I don't have much time."},
    {"tema": "Contables en plural (Negativo)", "detail": "Se usa 'many' para cosas que sí se cuentan.\nEj: I don't have many books."},
    {"tema": "Regla tras 'enjoy'", "detail": "Siempre va seguido de gerundio (-ing).\nEj: I enjoy reading (NO to read)."},
    {"tema": "Verbos que requieren '-ing'", "detail": "Enjoy (disfrutar), Mind (importar), Avoid (evitar), Finish (terminar)."},
    {"tema": "Voz Pasiva (Presente)", "detail": "Objeto + am/is/are + participio pasado.\nEj: Many cars are made in Germany."},
    {"tema": "Concordancia Pasiva", "detail": "Is made = Singular (The car is made).\nAre made = Plural (Many cars are made)."},
    {"tema": "Orden de adjetivos: OSASCOMP", "detail": "Opinion, Size, Age, Shape, Color, Origin, Material, Purpose."},
    {"tema": "Estructura Pasado Continuo", "detail": "Sujeto + was/were + verbo-ing.\nAcción en progreso en el pasado."},
    {"tema": "Diferencia 'much' vs 'a lot of'", "detail": "Much = Negativas/Preguntas.\nA lot of = Afirmativas (contable/incontable)."},
    {"tema": "Segundo Condicional", "detail": "If + Pasado Simple, would + infinitivo.\nSituaciones imaginarias o irreales."},
    {"tema": "Participios irregulares comunes", "detail": "Make -> Made (Hecho).\nBuy -> Bought (Comprado)."}
    ]